In [1]:
#User has to rate the event to get recommended for the similar events

In [2]:
import pandas as pd
from scipy import sparse
from sklearn.metrics.pairwise import cosine_similarity
ratings=pd.read_csv("eventdataset.csv",index_col=0)

In [3]:
pd.set_option('display.float_format', lambda x: '%.9f' % x)

In [4]:
ratings.fillna(0, inplace=True)
ratings

,RiverCleanUp,StreetCleanUp,ParkCleanUp,BloodDonation,FoodDonation,MoneyDonation,ClothDonation,ClimateChange,AnimalRescue,WildLifeConservation,Teaching,Counselling
user 1,4.000000000,5.000000000,3.000000000,0.000000000,2.000000000,1,3.000000000,5,1,2,5,5
user 2,5.000000000,3.000000000,3.000000000,2.000000000,2.000000000,2,0.000000000,4,3,2,3,2
user 3,1.000000000,0.000000000,0.000000000,4.000000000,5.000000000,4,4.000000000,3,2,3,1,2
user 4,0.000000000,2.000000000,1.000000000,4.000000000,0.000000000,3,3.000000000,2,4,5,2,1
user 5,1.000000000,0.000000000,2.000000000,3.000000000,3.000000000,4,2.000000000,2,5,4,3,4
user 6,3.000000000,4.000000000,5.000000000,2.000000000,1.000000000,0,1.000000000,4,2,2,3,4
user 7,5.000000000,5.000000000,5.000000000,3.000000000,3.000000000,0,5.000000000,5,3,3,4,4
user 8,1.000000000,1.000000000,1.000000000,5.000000000,5.000000000,5,5.000000000,3,5,5,3,3
user 9,2.000000000,2.000000000,2.000000000,5.000000000,5.000000000,4,4.000000000,3,4,5,3,3
user 10,3.000000000,2.000000000,3.000000000,4.000000000,2.000000000,1,3.000000000,4,4,3,5,5

In [5]:
def standardize(row):
    new_row = (row - row.mean())/(row.max()-row.min())
    return new_row

df_std = ratings.apply(standardize).T
print(df_std)

sparse_df = sparse.csr_matrix(df_std.values)
corrMatrix = pd.DataFrame(cosine_similarity(sparse_df),index=ratings.columns,columns=ratings.columns)
corrMatrix

                           user 1       user 2       user 3       user 4  \
RiverCleanUp          0.300000000  0.500000000 -0.300000000 -0.500000000
StreetCleanUp         0.520000000  0.120000000 -0.480000000 -0.080000000
ParkCleanUp           0.100000000  0.100000000 -0.500000000 -0.300000000
BloodDonation        -0.640000000 -0.240000000  0.160000000  0.160000000
FoodDonation         -0.160000000 -0.160000000  0.440000000 -0.560000000
MoneyDonation        -0.280000000 -0.080000000  0.320000000  0.120000000
ClothDonation         0.000000000 -0.600000000  0.200000000  0.000000000
ClimateChange         0.500000000  0.166666667 -0.166666667 -0.500000000
AnimalRescue         -0.575000000 -0.075000000 -0.325000000  0.175000000
WildLifeConservation -0.466666667 -0.466666667 -0.133333333  0.533333333
Teaching              0.450000000 -0.050000000 -0.550000000 -0.300000000
Counselling           0.425000000 -0.325000000 -0.325000000 -0.575000000

                           user 5       user 6       user 7       user 8  \
RiverCleanUp         -0.300000000  0.100000000  0.500000000 -0.300000000
StreetCleanUp        -0.480000000  0.320000000  0.520000000 -0.280000000
ParkCleanUp          -0.100000000  0.500000000  0.500000000 -0.300000000
BloodDonation        -0.040000000 -0.240000000 -0.040000000  0.360000000
FoodDonation          0.040000000 -0.360000000  0.040000000  0.440000000
MoneyDonation         0.320000000 -0.480000000 -0.480000000  0.520000000
ClothDonation        -0.200000000 -0.400000000  0.400000000  0.400000000
ClimateChange        -0.500000000  0.166666667  0.500000000 -0.166666667
AnimalRescue          0.425000000 -0.325000000 -0.075000000  0.425000000
WildLifeConservation  0.200000000 -0.466666667 -0.133333333  0.533333333
Teaching             -0.050000000 -0.050000000  0.200000000 -0.050000000
Counselling           0.175000000  0.175000000  0.175000000 -0.075000000

                           user 9      user 10
RiverCleanUp         -0.100000000  0.100000000
StreetCleanUp        -0.080000000 -0.080000000
ParkCleanUp          -0.100000000  0.100000000
BloodDonation         0.360000000  0.160000000
FoodDonation          0.440000000 -0.160000000
MoneyDonation         0.320000000 -0.280000000
ClothDonation         0.200000000  0.000000000
ClimateChange        -0.166666667  0.166666667
AnimalRescue          0.175000000  0.175000000
WildLifeConservation  0.533333333 -0.133333333
Teaching             -0.050000000  0.450000000
Counselling          -0.075000000  0.425000000

,RiverCleanUp,StreetCleanUp,ParkCleanUp,BloodDonation,FoodDonation,MoneyDonation,ClothDonation,ClimateChange,AnimalRescue,WildLifeConservation,Teaching,Counselling
RiverCleanUp,1.000000000,0.781391377,0.775797523,-0.604563542,-0.178276062,-0.747417839,-0.267651690,0.896013635,-0.490178130,-0.740436097,0.609521967,0.443494499
StreetCleanUp,0.781391377,1.000000000,0.806125848,-0.655610068,-0.455703746,-0.842105263,-0.111065415,0.839575618,-0.596656260,-0.554421357,0.600003225,0.397770840
ParkCleanUp,0.775797523,0.806125848,1.000000000,-0.521640531,-0.423014352,-0.879410016,-0.288675135,0.717001639,-0.327278425,-0.585636851,0.602615348,0.579031060
BloodDonation,-0.604563542,-0.655610068,-0.521640531,1.000000000,0.507855627,0.632195423,0.527046277,-0.597614305,0.718563221,0.805156351,-0.431753026,-0.407543320
FoodDonation,-0.178276062,-0.455703746,-0.423014352,0.507855627,1.000000000,0.614509597,0.582815505,-0.117484563,0.218217890,0.341093250,-0.237429040,-0.018975469
MoneyDonation,-0.747417839,-0.842105263,-0.879410016,0.632195423,0.614509597,1.000000000,0.296174439,-0.783603910,0.578575767,0.736042146,-0.580330988,-0.506253796
ClothDonation,-0.267651690,-0.111065415,-0.288675135,0.527046277,0.582815505,0.296174439,1.000000000,0.000000000,0.203489232,0.537914354,-0.000000000,0.050872308
ClimateChange,0.896013635,0.839575618,0.717001639,-0.597614305,-0.117484563,-0.783603910,0.000000000,1.000000000,-0.653749452,-0.731925055,0.669461927,0.576837752
AnimalRescue,-0.490178130,-0.596656260,-0.327278425,0.718563221,0.218217890,0.578575767,0.203489232,-0.653749452,1.000000000,0.774975233,-0.108127856,-0.180124224
WildLifeConservation,-0.740436097,-0.554421357,-0.585636851,0.805156351,0.341093250,0.736042146,0.537914354,-0.731925055,0.774975233,1.000000000,-0.342997170,-0.407190377
Teaching,0.609521967,0.600003225,0.602615348,-0.431753026,-0.237429040,-0.580330988,-0.000000000,0.669461927,-0.108127856,-0.342997170,1.000000000,0.837990882
Counselling,0.443494499,0.397770840,0.579031060,-0.407543320,-0.018975469,-0.506253796,0.050872308,0.576837752,-0.180124224,-0.407190377,0.837990882,1.000000000

In [6]:
corrMatrix = ratings.corr(method='pearson')
corrMatrix.head(6)

,RiverCleanUp,StreetCleanUp,ParkCleanUp,BloodDonation,FoodDonation,MoneyDonation,ClothDonation,ClimateChange,AnimalRescue,WildLifeConservation,Teaching,Counselling
RiverCleanUp,1.000000000,0.781391377,0.775797523,-0.604563542,-0.178276062,-0.747417839,-0.267651690,0.896013635,-0.490178130,-0.740436097,0.609521967,0.443494499
StreetCleanUp,0.781391377,1.000000000,0.806125848,-0.655610068,-0.455703746,-0.842105263,-0.111065415,0.839575618,-0.596656260,-0.554421357,0.600003225,0.397770840
ParkCleanUp,0.775797523,0.806125848,1.000000000,-0.521640531,-0.423014352,-0.879410016,-0.288675135,0.717001639,-0.327278425,-0.585636851,0.602615348,0.579031060
BloodDonation,-0.604563542,-0.655610068,-0.521640531,1.000000000,0.507855627,0.632195423,0.527046277,-0.597614305,0.718563221,0.805156351,-0.431753026,-0.407543320
FoodDonation,-0.178276062,-0.455703746,-0.423014352,0.507855627,1.000000000,0.614509597,0.582815505,-0.117484563,0.218217890,0.341093250,-0.237429040,-0.018975469
MoneyDonation,-0.747417839,-0.842105263,-0.879410016,0.632195423,0.614509597,1.000000000,0.296174439,-0.783603910,0.578575767,0.736042146,-0.580330988,-0.506253796

In [7]:
def get_similar(event_name,rating):
    similar_score = corrMatrix[event_name]*(rating-2.5)
    similar_score = similar_score.sort_values(ascending=False)
    return similar_score

In [8]:
cleanup_lover = [("RiverCleanUp",5),("ClothDonation",1),("FoodDonation",1)]
similar_scores = pd.DataFrame()
for movie,rating in cleanup_lover:
    similar_scores = similar_scores.append(get_similar(movie,rating),ignore_index = True)

similar_scores.head(10)

,AnimalRescue,BloodDonation,ClimateChange,ClothDonation,Counselling,FoodDonation,MoneyDonation,ParkCleanUp,RiverCleanUp,StreetCleanUp,Teaching,WildLifeConservation
0,-1.225445326,-1.511408854,2.240034088,-0.669129224,1.108736247,-0.445690156,-1.868544597,1.939493809,2.500000000,1.953478442,1.523804917,-1.851090243
1,-0.305233848,-0.790569415,0.000000000,-1.500000000,-0.076308462,-0.874223258,-0.444261658,0.433012702,0.401477534,0.166598122,-0.000000000,-0.806871530
2,-0.327326835,-0.761783440,0.176226844,-0.874223258,0.028463203,-1.500000000,-0.921764395,0.634521527,0.267414094,0.683555619,0.356143560,-0.511639876

In [9]:
similar_scores.sum().sort_values(ascending=False)

RiverCleanUp            3.168891628
ParkCleanUp             3.007028038
StreetCleanUp           2.803632183
ClimateChange           2.416260932
Teaching                1.879948477
Counselling             1.060890988
AnimalRescue           -1.858006009
FoodDonation           -2.819913414
ClothDonation          -3.043352482
BloodDonation          -3.063761710
WildLifeConservation   -3.169601649
MoneyDonation          -3.234570650
dtype: float64

In [10]:
print(get_similar('ClothDonation',3))

ClothDonation           0.500000000
FoodDonation            0.291407753
WildLifeConservation    0.268957177
BloodDonation           0.263523138
MoneyDonation           0.148087219
AnimalRescue            0.101744616
Counselling             0.025436154
Teaching                0.000000000
ClimateChange          -0.000000000
StreetCleanUp          -0.055532707
RiverCleanUp           -0.133825845
ParkCleanUp            -0.144337567
Name: ClothDonation, dtype: float64